module.exports = {
    GET_CONNECTIONS: 'GET_CONNECTIONS',
    REQUEST_CONNECTIONS: 'REQUEST_CONNECTIONS',
    REQUEST_IG_IMAGES: 'REQUEST_IG_IMAGES',
    GET_IG_IMAGES: 'GET_IG_IMAGES',
    GET_DB_POSTS: 'GET_DB_POSTS',
    REQUEST_DB_POSTS: 'REQUEST_DB_POSTS',
    SAVING_IG_ACCESS_TOKEN: 'SAVING_IG_ACCESS_TOKEN',
    SAVED_IG_ACCESS_TOKEN: 'SAVED_IG_ACCESS_TOKEN',
    INSERTING_POST: 'INSERTING_POST',
    INSERTING_POST_COMPLETE: 'INSERTING_POST_COMPLETE',
}
